export function generateSearchScript(dbFilename: string): string {
  return `#!/usr/bin/env bash
# Overview search - queries the code index database
# Generated by: overview index
#
# Usage:
#   .overview/search "query"                  search everything
#   .overview/search "query" --only files     only files
#   .overview/search "query" --only symbols   only functions/classes
#   .overview/search "query" --only modules   compact module summaries
#   .overview/search "query" --only imports   only import relations
#   .overview/search "query" --module Auth    filter by module
#   .overview/search "query" --kind view      filter by kind
#   .overview/search "query" --with-imports   include imports in mixed search output
#   .overview/search "query" --limit 20       more results (default: 5)

DB="$(dirname "$0")/${dbFilename}"

if [ ! -f "$DB" ]; then
  echo '{"error":"Database not found. Run: overview index"}' >&2
  exit 1
fi

if ! command -v sqlite3 >/dev/null 2>&1; then
  echo '{"error":"sqlite3 not found. Install: brew install sqlite"}' >&2
  exit 1
fi

run_sql() {
  sqlite3 -cmd ".timeout 5000" "$DB"
}

sanitize_literal() {
  printf '%s' "$1" | tr '\\n' ' ' | tr -d "'\\""
}

json_or_empty() {
  if [ -n "$1" ]; then
    printf '%s\\n' "$1"
  else
    echo "[]"
  fi
}

QUERY=""
ONLY=""
MODULE=""
KIND=""
WITH_IMPORTS=0
LIMIT=5

while [[ $# -gt 0 ]]; do
  case "$1" in
    --only)   ONLY="$2"; shift 2 ;;
    --module) MODULE="$2"; shift 2 ;;
    --kind)   KIND="$2"; shift 2 ;;
    --with-imports) WITH_IMPORTS=1; shift ;;
    --limit)  LIMIT="$2"; shift 2 ;;
    -h|--help)
      grep "^#" "$0" | sed 's/^# //;s/^#//'
      exit 0
      ;;
    *)
      QUERY="$1"
      shift
      ;;
  esac
done

if [ -z "$QUERY" ]; then
  echo "Usage: .overview/search \\"query\\" [--only files|symbols|modules|imports] [--module name] [--kind kind] [--with-imports] [--limit n]" >&2
  exit 1
fi

if ! [[ "$LIMIT" =~ ^[0-9]+$ ]]; then
  echo '{"error":"--limit must be a positive integer"}' >&2
  exit 1
fi

SAFE_QUERY="$(sanitize_literal "$QUERY")"
SAFE_MODULE="$(sanitize_literal "$MODULE")"
SAFE_KIND="$(sanitize_literal "$KIND")"

MOD_FILTER=""
KIND_FILTER=""
[ -n "$SAFE_MODULE" ] && MOD_FILTER="AND f.module = '$SAFE_MODULE'"
[ -n "$SAFE_KIND" ] && KIND_FILTER="AND f.kind = '$SAFE_KIND'"

search_files() {
  cat <<SQL | run_sql
SELECT COALESCE(json_group_array(json_object(
  'path', path,
  'module', module,
  'layer', layer,
  'kind', kind,
  'description', description,
  'tags', json(tags),
  'llm', llm,
  'updated_at', updated_at,
  'has_error', has_error
)), '[]')
FROM (
  SELECT
    f.path,
    f.module,
    f.layer,
    f.kind,
    f.description,
    f.tags,
    f.llm,
    f.updated_at,
    f.has_error
  FROM files f
  WHERE (
    f.rowid IN (
      SELECT rowid FROM files_fts
      WHERE files_fts MATCH '"$SAFE_QUERY"'
    )
    OR lower(f.path) LIKE lower('%$SAFE_QUERY%')
    OR lower(f.description) LIKE lower('%$SAFE_QUERY%')
    OR EXISTS (
      SELECT 1
      FROM json_each(f.tags)
      WHERE lower(value) LIKE lower('%$SAFE_QUERY%')
    )
  )
  $MOD_FILTER $KIND_FILTER
  ORDER BY
    CASE
      WHEN lower(f.path) = lower('$SAFE_QUERY') THEN 5
      WHEN lower(f.path) LIKE lower('$SAFE_QUERY%') THEN 4
      WHEN lower(f.path) LIKE lower('%$SAFE_QUERY%') THEN 3
      WHEN lower(f.description) LIKE lower('%$SAFE_QUERY%') THEN 2
      ELSE 1
    END DESC,
    length(f.path),
    f.path
  LIMIT $LIMIT
);
SQL
}

search_symbols() {
  cat <<SQL | run_sql
SELECT COALESCE(json_group_array(json_object(
  'name', name,
  'type', type,
  'description', description,
  'line', line,
  'file', file,
  'module', module,
  'kind', kind
)), '[]')
FROM (
  SELECT
    s.name,
    s.type,
    s.description,
    s.line,
    s.file_path AS file,
    f.module,
    f.kind
  FROM symbols s
  JOIN files f ON f.path = s.file_path
  WHERE (
    s.id IN (
      SELECT rowid FROM symbols_fts
      WHERE symbols_fts MATCH '"$SAFE_QUERY"'
    )
    OR lower(s.name) LIKE lower('%$SAFE_QUERY%')
    OR lower(s.description) LIKE lower('%$SAFE_QUERY%')
    OR lower(s.file_path) LIKE lower('%$SAFE_QUERY%')
  )
  $MOD_FILTER $KIND_FILTER
  ORDER BY
    CASE
      WHEN lower(s.name) = lower('$SAFE_QUERY') THEN 5
      WHEN lower(s.name) LIKE lower('$SAFE_QUERY%') THEN 4
      WHEN lower(s.name) LIKE lower('%$SAFE_QUERY%') THEN 3
      WHEN lower(s.file_path) LIKE lower('%$SAFE_QUERY%') THEN 2
      ELSE 1
    END DESC,
    COALESCE(s.line, 999999),
    s.file_path
  LIMIT $LIMIT
);
SQL
}

search_imports() {
  cat <<SQL | run_sql
SELECT COALESCE(json_group_array(json_object(
  'direction', direction,
  'path', path
)), '[]')
FROM (
  SELECT 'uses' AS direction, to_path AS path
  FROM imports
  WHERE from_path LIKE '%$SAFE_QUERY%'
  UNION ALL
  SELECT 'used_by' AS direction, from_path AS path
  FROM imports
  WHERE to_path LIKE '%$SAFE_QUERY%'
  LIMIT $LIMIT
);
SQL
}

search_modules() {
  cat <<SQL | run_sql
SELECT COALESCE(json_group_array(json_object(
  'module', module,
  'fileCount', file_count,
  'symbolCount', symbol_count,
  'sampleFiles', json(sample_files),
  'summary', summary
)), '[]')
FROM (
  SELECT
    m.module,
    m.file_count,
    (
      SELECT COUNT(*)
      FROM symbols s
      JOIN files f2 ON f2.path = s.file_path
      WHERE f2.module = m.module
    ) AS symbol_count,
    COALESCE((
      SELECT json_group_array(path)
      FROM (
        SELECT path
        FROM files
        WHERE module = m.module
        ORDER BY path
        LIMIT 3
      )
    ), '[]') AS sample_files,
    printf(
      '%d files | %d symbols',
      m.file_count,
      (
        SELECT COUNT(*)
        FROM symbols s
        JOIN files f3 ON f3.path = s.file_path
        WHERE f3.module = m.module
      )
    ) AS summary
  FROM (
    SELECT module, COUNT(*) AS file_count
    FROM files
    WHERE module != ''
    GROUP BY module
  ) m
  WHERE lower(m.module) LIKE lower('%$SAFE_QUERY%')
  ORDER BY
    CASE
      WHEN lower(m.module) = lower('$SAFE_QUERY') THEN 3
      WHEN lower(m.module) LIKE lower('$SAFE_QUERY%') THEN 2
      ELSE 1
    END DESC,
    m.file_count DESC,
    m.module
  LIMIT $LIMIT
);
SQL
}

case "$ONLY" in
  files)
    FILES="$(search_files)"
    printf '{"query":"%s","files":%s}\\n' "$QUERY" "$(json_or_empty "$FILES")"
    ;;
  symbols)
    SYMBOLS="$(search_symbols)"
    printf '{"query":"%s","symbols":%s}\\n' "$QUERY" "$(json_or_empty "$SYMBOLS")"
    ;;
  modules)
    MODULES="$(search_modules)"
    printf '{"query":"%s","modules":%s}\\n' "$QUERY" "$(json_or_empty "$MODULES")"
    ;;
  imports)
    IMPORTS="$(search_imports)"
    printf '{"query":"%s","imports":%s}\\n' "$QUERY" "$(json_or_empty "$IMPORTS")"
    ;;
  "")
    MODULES="$(search_modules)"
    FILES="$(search_files)"
    SYMBOLS="$(search_symbols)"
    if [ "$WITH_IMPORTS" = "1" ]; then
      IMPORTS="$(search_imports)"
      printf '{"query":"%s","modules":%s,"files":%s,"symbols":%s,"imports":%s}\\n' \\
        "$QUERY" "$(json_or_empty "$MODULES")" "$(json_or_empty "$FILES")" "$(json_or_empty "$SYMBOLS")" "$(json_or_empty "$IMPORTS")"
    else
      printf '{"query":"%s","modules":%s,"files":%s,"symbols":%s,"imports":[]}\\n' \\
        "$QUERY" "$(json_or_empty "$MODULES")" "$(json_or_empty "$FILES")" "$(json_or_empty "$SYMBOLS")"
    fi
    ;;
  *)
    echo "Unknown --only: $ONLY (use: files, symbols, modules, imports)" >&2
    exit 1
    ;;
esac
`;
}
