export function generateSearchScript(dbFilename: string): string {
  return `#!/usr/bin/env bash
# Overview search - queries the code index database
# Generated by: overview index
#
# Usage:
#   .overview/search "query"                  search everything
#   .overview/search "query" --only files     only files
#   .overview/search "query" --only symbols   only functions/classes
#   .overview/search "query" --only imports   only import relations
#   .overview/search "query" --module Auth    filter by module
#   .overview/search "query" --kind view      filter by kind
#   .overview/search "query" --limit 20       more results (default: 10)

DB="$(dirname "$0")/${dbFilename}"

if [ ! -f "$DB" ]; then
  echo '{"error":"Database not found. Run: overview index"}' >&2
  exit 1
fi

if ! command -v sqlite3 >/dev/null 2>&1; then
  echo '{"error":"sqlite3 not found. Install: brew install sqlite"}' >&2
  exit 1
fi

run_sql() {
  sqlite3 -cmd ".timeout 5000" "$DB"
}

sanitize_literal() {
  printf '%s' "$1" | tr '\\n' ' ' | tr -d "'\\""
}

json_or_empty() {
  if [ -n "$1" ]; then
    printf '%s\\n' "$1"
  else
    echo "[]"
  fi
}

QUERY=""
ONLY=""
MODULE=""
KIND=""
LIMIT=10

while [[ $# -gt 0 ]]; do
  case "$1" in
    --only)   ONLY="$2"; shift 2 ;;
    --module) MODULE="$2"; shift 2 ;;
    --kind)   KIND="$2"; shift 2 ;;
    --limit)  LIMIT="$2"; shift 2 ;;
    -h|--help)
      grep "^#" "$0" | sed 's/^# //;s/^#//'
      exit 0
      ;;
    *)
      QUERY="$1"
      shift
      ;;
  esac
done

if [ -z "$QUERY" ]; then
  echo "Usage: .overview/search \\"query\\" [--only files|symbols|imports] [--module name] [--kind kind] [--limit n]" >&2
  exit 1
fi

if ! [[ "$LIMIT" =~ ^[0-9]+$ ]]; then
  echo '{"error":"--limit must be a positive integer"}' >&2
  exit 1
fi

SAFE_QUERY="$(sanitize_literal "$QUERY")"
SAFE_MODULE="$(sanitize_literal "$MODULE")"
SAFE_KIND="$(sanitize_literal "$KIND")"

MOD_FILTER=""
KIND_FILTER=""
[ -n "$SAFE_MODULE" ] && MOD_FILTER="AND f.module = '$SAFE_MODULE'"
[ -n "$SAFE_KIND" ] && KIND_FILTER="AND f.kind = '$SAFE_KIND'"

search_files() {
  cat <<SQL | run_sql
SELECT COALESCE(json_group_array(json_object(
  'path', path,
  'module', module,
  'layer', layer,
  'kind', kind,
  'description', description,
  'tags', json(tags),
  'llm', llm,
  'updated_at', updated_at,
  'has_error', has_error
)), '[]')
FROM (
  SELECT
    f.path,
    f.module,
    f.layer,
    f.kind,
    f.description,
    f.tags,
    f.llm,
    f.updated_at,
    f.has_error
  FROM files f
  WHERE f.rowid IN (
    SELECT rowid FROM files_fts
    WHERE files_fts MATCH '"$SAFE_QUERY"'
  )
  $MOD_FILTER $KIND_FILTER
  LIMIT $LIMIT
);
SQL
}

search_symbols() {
  cat <<SQL | run_sql
SELECT COALESCE(json_group_array(json_object(
  'name', name,
  'type', type,
  'description', description,
  'line', line,
  'file', file,
  'module', module,
  'kind', kind
)), '[]')
FROM (
  SELECT
    s.name,
    s.type,
    s.description,
    s.line,
    s.file_path AS file,
    f.module,
    f.kind
  FROM symbols s
  JOIN files f ON f.path = s.file_path
  WHERE s.id IN (
    SELECT rowid FROM symbols_fts
    WHERE symbols_fts MATCH '"$SAFE_QUERY"'
  )
  $MOD_FILTER $KIND_FILTER
  LIMIT $LIMIT
);
SQL
}

search_imports() {
  cat <<SQL | run_sql
SELECT COALESCE(json_group_array(json_object(
  'direction', direction,
  'path', path
)), '[]')
FROM (
  SELECT 'uses' AS direction, to_path AS path
  FROM imports
  WHERE from_path LIKE '%$SAFE_QUERY%'
  UNION ALL
  SELECT 'used_by' AS direction, from_path AS path
  FROM imports
  WHERE to_path LIKE '%$SAFE_QUERY%'
  LIMIT $LIMIT
);
SQL
}

case "$ONLY" in
  files)
    FILES="$(search_files)"
    printf '{"query":"%s","files":%s}\\n' "$QUERY" "$(json_or_empty "$FILES")"
    ;;
  symbols)
    SYMBOLS="$(search_symbols)"
    printf '{"query":"%s","symbols":%s}\\n' "$QUERY" "$(json_or_empty "$SYMBOLS")"
    ;;
  imports)
    IMPORTS="$(search_imports)"
    printf '{"query":"%s","imports":%s}\\n' "$QUERY" "$(json_or_empty "$IMPORTS")"
    ;;
  "")
    FILES="$(search_files)"
    SYMBOLS="$(search_symbols)"
    IMPORTS="$(search_imports)"
    printf '{"query":"%s","files":%s,"symbols":%s,"imports":%s}\\n' \\
      "$QUERY" "$(json_or_empty "$FILES")" "$(json_or_empty "$SYMBOLS")" "$(json_or_empty "$IMPORTS")"
    ;;
  *)
    echo "Unknown --only: $ONLY (use: files, symbols, imports)" >&2
    exit 1
    ;;
esac
`;
}
